### ISSUE TITLE
[FE/BE] 7기 홍보 전 전체 QA를 진행한다. 

### ISSUE THREAD

**Issue by healim01** [woowacourse-teams/2024-bang-ggood#1032]
### 발견한 에러 상황 / 캡쳐본과 함께 업로드 해주세요

**Comment by skiende74** [comment]
![image](https://github.com/user-attachments/assets/43ef6731-b446-4cb8-9405-a335792e1135)
아티클엑박
재연방법 : /article/5 접속

**Comment by tkdgur0906** [comment]
<img width="624" alt="스크린샷 2024-12-06 오후 10 42 11" src="https://github.com/user-attachments/assets/bac49329-8a1c-4dd0-b6e5-8f1e2874eb31">
기본정보 카테고리에서 이전으로 가기 하면 아무것도 안나오는 증상

**Comment by tkdgur0906** [comment]
<img width="300" alt="스크린샷 2024-12-06 오후 10 43 47" src="https://github.com/user-attachments/assets/9ac7f51b-1f13-4810-b9ed-2b55f9903160">

아무것도 선택안한 카테고리가 있는 경우, 이전이나 이후 카테고리에서 `이전으로가기`, `다음으로가기` 하면 에러페이지 나오는 증상

**Comment by tkdgur0906** [comment]
<img width="300" alt="스크린샷 2024-12-06 오후 10 46 11" src="https://github.com/user-attachments/assets/05e18cc8-6a9b-47f6-8378-52087781d01a">

외부 카테고리에서 `다음으로가기` 하면 기본정보로 안가고 옵션으로 이동하는 증상

**Comment by tsulocalize** [comment]
![스크린샷 2024-12-06 오후 10.40.09.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/9a4bc815-34f1-475c-b645-ef67d37c2f4a/51d7f572-b3b0-42d6-95c5-22a8e3b210cf/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2024-12-06_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_10.40.09.png)
구분 기호가 “/” 와 “+” 2개라서 헷갈림

**Comment by tkdgur0906** [comment]
<img width="727" alt="스크린샷 2024-12-06 오후 11 09 06" src="https://github.com/user-attachments/assets/9a924d3a-2131-45a7-bb72-b92f63ccc34d">

이미 존재하는 이메일인 경우 에러 처리가 안되어있음

**Comment by tsulocalize** [comment]
[방 비교하기]에서 순서를 반대로 클릭해서 보내면 A방과 B방의 지도 핀을 반대로 꽂아줌  
<img width="587" alt="스크린샷 2024-12-06 오후 10 46 18" src="https://github.com/user-attachments/assets/d4a7fef4-b0ae-4cb1-89df-1710b533f4a3">

**Comment by tsulocalize** [comment]
[옥탑]은 층수를 입력받지 않는데(백앤드), 층수 입력이 됨(프론트) 
<img width="393" alt="스크린샷 2024-12-06 오후 10 43 18" src="https://github.com/user-attachments/assets/d50b58a9-06c6-49c7-a4f8-691e7b10976d">

**Comment by tsulocalize** [comment]
한줄평 입력 시 글자 수가 16/15가 됨
<img width="445" alt="스크린샷 2024-12-06 오후 10 42 20" src="https://github.com/user-attachments/assets/fe7e550f-2d63-429c-ba0f-c3a3c660e316">
