### ISSUE TITLE
배포시 발생한 에러를 해결한다. 

### ISSUE THREAD

**Issue by ooherin** [woowacourse-teams/2024-bang-ggood#127]
## 🐛 어떤 버그인가요?

체크리스트 리스트 페이지
- [x] 체크리스트 옵션 선택 페이지에서 버튼을 눌렀을 때 넘어가지 않는 에러 
- [x] 리스트가 밑으로 내려가지 않는 에러
-  [x] 페이지가 밑으로 내려가는 에러 (탭 고정x)

- [ ] 체크리스트 감정이 탭 이동했을 때 체크리스트 답변이 저장되지 않는 에러
- [x] 하단 탭이 밑에 붙어있지 않는 에러 
- [x] 하단 탭을 눌렀을 때 나는 페이지 에러 

### 추가

- 체크리스트 저장시 알림 나타나게 하기

**Comment by healim01** [comment]
- [ ] 플로팅 버튼 위치 수정 필요

**Comment by healim01** [comment]
- 체크리스트 옵션 선택 페이지에서 버튼을 눌렀을 때 넘어가지 않는 에러 : 해결 ✅

**Comment by healim01** [comment]
- 체크리스트 리스트가 밑으로 내려가지 않는 에러: 해결 ✅

**Comment by healim01** [comment]
layout 에도 overflow-y: scroll 넣어놨습니다.

**Comment by healim01** [comment]
방 비교 페이지 레이아웃이 깨지는 오류도 수정해놨습니다.

**Comment by healim01** [comment]
404 페이지 만들어서 페이지 현재 없는 페이지는 404가 뜰 수 있게 만들었습니다.

**Comment by healim01** [comment]
리안이 작업하시는 체크 상태 빼고 모두 해결해서 PR 올립니다.
