### ISSUE TITLE
스토리북 크로마틱 배포를 진행한다. 

### ISSUE THREAD

**Issue by healim01** [woowacourse-teams/2024-bang-ggood#32]
## ✨ 구현할 기능이 무엇인가요? 
- 진행한 스토리북 기능들 크로마틱 배포 

## ✅ 해야할 테스크들을 작성해주세요. 
- [x] 크로마틱 연결
-  [x] 크로마틱 배포

**Comment by skiende74** [comment]
CI (크로마틱 배포) CD (배포 생성) 은 완료되었으니 close해주세요
배포링크 comment on PR은 이슈를 새로 팠습니다.
