### ISSUE TITLE
아코디언 컴포넌트를 공용 컴포넌트로 수정한다. 

### ISSUE THREAD

**Issue by ooherin** [woowacourse-teams/2024-bang-ggood#38]
## ✨ 구현할 기능이 무엇인가요? 

기존의 아코디언 컴포넌트를 공용으로 사용할 수 있도록 수정합니다. 

## ⏰ 소요시간

2-3시간

**Comment by healim01** [comment]
완료되셨으면 이슈 클로스 해주세요~!
