### ISSUE TITLE
[FE] 2차 QA를 진행한다. 

### ISSUE THREAD

**Issue by healim01** [woowacourse-teams/2024-bang-ggood#484]
## ✨ 구현할 기능이 무엇인가요? 

- [FE] 2차 QA를 진행한다.

**Comment by healim01** [comment]
1. 선택 개수가 static 으로 되어있다. 
<img width="450" alt="스크린샷 2024-08-21 오후 3 06 22" src="https://github.com/user-attachments/assets/4bd2cf18-dfca-4fb5-80fa-a639795bb21a">

<img width="781" alt="스크린샷 2024-08-21 오후 3 06 58" src="https://github.com/user-attachments/assets/c7526401-e2e7-49d5-b0c0-1a913cf8ef28">

**Comment by healim01** [comment]
2. 선택된 질문이 하이라이팅이 안된다. 

-> 백엔드 프로퍼티 문제 확인

**Comment by healim01** [comment]
3. highlight 프로퍼티 백엔드와 다름 

-> 프론트에서 `highlights` 로 수정

**Comment by healim01** [comment]
4. n번째 방이 예시용을 추가로 2번째로 진행된다.

**Comment by healim01** [comment]
5. 옵션 클릭이 정상 작동 안됨 (아이폰에게만)

**Comment by healim01** [comment]
6. 팁 박스 폰트 사이즈가 다르다

**Comment by healim01** [comment]
7. 메모 오토 포커스가 맨 앞으로 간다

**Comment by skiende74** [comment]
![image](https://github.com/user-attachments/assets/3a6fc233-d63d-47c2-9511-fc22fd1282a0)

**Comment by healim01** [comment]
8. 토스트 에러 메세지를 사용자 친화적으로 리팩토링 필요

**Comment by healim01** [comment]
10. md 파일 다크모드 disable 진행하기

**Comment by healim01** [comment]
11. 지하철에 역이 함께 전달되지 않는다.

**Comment by skiende74** [comment]
12. minor : 커스텀 체크리스트에서, 디폴트탭 체크리스트를 모두선택안할경우
탭이그냥선택안된상태가된다

**Comment by skiende74** [comment]
13. 디테일페이지 : kakao = {window} 가 빈 객체라 maps 어쩌구 에러가난다

**Comment by skiende74** [comment]
14. 새 체크리스트 나갔다 들어왔을 때, 기본정보는 살아있지만 OX 정보는 날아간다.

-> 그리고 persist도 되는게 좋다

**Comment by healim01** [comment]
15. 스켈레톤 안된 페이지 작업

**Comment by healim01** [comment]
- 추가 이슈 
- #529

**Comment by skiende74** [comment]
16. 체크리스트 수정에서 post말고 put이 날아가야함

**Comment by skiende74** [comment]
17. 수정페이지에서 방이름이 비어있으면 체크리스트없다면서 표시안되는현상
18. 입력을 비워뒀을때 전송누르면 자동으로 value가 N번째방으로 채워서 전송되게하기
