### ISSUE TITLE
[FE] QA - 모바일에서 UI 깨지거나 부족한 부분, 스켈레톤이 없는 부분을 고친다.

### ISSUE THREAD

**Issue by healim01** [woowacourse-teams/2024-bang-ggood#529]
## ✨ 구현할 기능이 무엇인가요? 

- QA - 모바일에서 UI 깨지거나 부족한 부분을 고친다.

## ✅ 해야할 테스크들을 작성해주세요. 

- [x] 메인 페이지 간격 마진 줄이기 
- [x] 아티클 디테일 스켈레톤 추가하기 
- [x] 100vh 모바일 사이즈 확인해서 불필요한 스크롤 막기
- [ ] 아티클 리스트 스크롤 확인하기  
- [x] 체크리스트 디테일 좋아요 확인하기 
- [x] 헤더 사이즈 줄이기

**Comment by skiende74** [comment]
디테일 좋아요 하였음. #546
