### ISSUE TITLE
[FE] 새 체크리스트의 버그, 수정사항을 해결한다.

### ISSUE THREAD

**Issue by skiende74** [woowacourse-teams/2024-bang-ggood#572]
## ✅ 해야할 테스크들을 작성해주세요. 
- [x] 가끔 검증 어긋나는 것도 입력가능한 현상 해결
- [x] 자잘한 UI 수정
- [ ] 좋아요 버그 수정
## ⏰ 소요시간
3h

**Comment by healim01** [comment]
좋아요 버그는 제가 따로 진행해서 이슈 닫습니다~
