### ISSUE TITLE
[BE] 체크리스트 리스트 조회 API를 리팩토링한다.

### ISSUE THREAD

**Issue by JINU-CHANG** [woowacourse-teams/2024-bang-ggood#617]
## ✨ 구현할 기능이 무엇인가요?

- 체크리스트 리스트 조회 API 리팩토링 

## ⏰ 소요시간

- 1hr

**Comment by andreyfmc** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive
