### ISSUE TITLE
헤더 컴포넌트의 중앙에도 컨텐츠를 넣을 수 있게 한다.

### ISSUE THREAD

**Issue by skiende74** [woowacourse-teams/2024-bang-ggood#64]
## ✨ 구현할 기능이 무엇인가요? 
- center prop도 받게 조정
## ✅ 해야할 테스크들을 작성해주세요. 
- center prop도 받게 조정
## ⏰ 소요시간
- 20m

**Comment by ooherin** [comment]
해당 컴포넌트 일부 수정완료
