### ISSUE TITLE
[FE] 좋아요 버튼의 레이아웃 디자인을 논의한다.

### ISSUE THREAD

**Issue by skiende74** [woowacourse-teams/2024-bang-ggood#833]
## ✨ 논의할 내용이 무엇인가요? 
#817 에서 논의중
모바일에서 제목이 2줄되는현상을 막기위해
"방 둘러볼 때 꼭 필요한 체크리스트" -> "내가 둘러본 방" 으로 고친 것과 관련한 대화

### 기존대화

> 제이드 : 모바일에서 제목이 2줄되는현상을 막기위해
"방 둘러볼 때 꼭 필요한 체크리스트" -> "내가 둘러본 방" 으로 고쳤는데
어떻게생각하시는지도 궁금합니다.

> 헤일리 : 흠.. 이 부분은 기존 워딩이 이 좋은거 같습니다. 저렇게 지정한 이유가 아티클과 더불어 메인페이지에서도 함께 맞춰서 정해진 워딩이라서요. 피그마에 대략 레이아웃 추가해놓겠습니다. 골라보면 좋을거 같아요!

> 리안 : 워딩에 관해서 개인적인 의견을 말씀 드리자면, 기존에 '방을 꼭 둘러볼때~' 라는 문구는 길기도 하고 홍보문구의 색이 강해서 제이드가 바꾼 버전이 더 나은 것 같습니다. 사실 홍보용도 나쁘지 않긴 한데, 저런 서브 타이틀에서는 직관성, 이해성이 먼저라고 생각해서요. '내가 둘러본 방' => '체크리스트 리스트' 가 더 잘 이어지는 것 같아요!

### 현재 UI
![image](https://github.com/user-attachments/assets/b74fa3e7-3c3c-40dc-9299-038a4b0a6504)

## ✅ 해야할 테스크들을 작성해주세요. 
- [x] 문구 확정
- [x] 레이아웃 디자인 확정

완료 시 추후 PR에서 변경사항을 구현한다.

**Comment by skiende74** [comment]
@healim01 
피그마에 남겨주신 레이아웃 보았는데,
제목글자 폰트가 커서 저 글자수라면 2줄이 됩니다.

![image](https://github.com/user-attachments/assets/652b0cc7-b9f8-41d3-9093-82053c01daa5)

----

문구를 고친 것은 2줄이 되는 걸 해결하기위한 것도 있지만
`체크리스트`라는 표현이 너무많이쓰여서 피하고싶은것도 있는데요

메인페이지와의 일관성을 생각하고 있으시다면
메인페이지의 "나의 체크리스트" 도 -> "내가 둘러본 방"
으로 고쳐서

둘을 통일하면 어떨까요

**Comment by ooherin** [comment]
![스크린샷 2024-10-18 오후 2 09 30](https://github.com/user-attachments/assets/9df9a411-1d1a-414b-9f95-a9b631bf4169)

비슷한 이슈라서 같이 올립니다! 위에 모바일 버전으로 봤을 떄 텍스트가 깨지는데
`새로운 방 추가하기 / 기록하기` 로 수정하는 게 어떨까 싶네요~

**Comment by skiende74** [comment]
전체투표결과 "내가 둘러본 방" & 좋아요 패턴으로 결정되어 논의를 닫습니다.
